# News
-
  name: 'Single News'
  uriPattern: '{node}/show/{--newsDetail.news}.{@format}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--newsDetail':
      '@package': 'Lelesys.Plugin.News'
      '@controller': 'News'
      '@action': 'show'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
    '--newsDetail.news':
      objectType: 'Lelesys\Plugin\News\Domain\Model\News'
      uriPattern: '{title}'
  appendExceedingArguments: TRUE

-
  name: 'Show Category News'
  uriPattern: '{node}/category/{--newsList.category}.{@format}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--newsList':
      '@package': 'Lelesys.Plugin.News'
      '@controller': 'News'
      '@action': 'index'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

-
  name: 'Show Folder News'
  uriPattern: '{node}/folder/{--newsList.folder}.{@format}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--newsList':
      '@package': 'Lelesys.Plugin.News'
      '@controller': 'News'
      '@action': 'index'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

# tag
-
  name: 'Show Tag News'
  uriPattern: '{node}/tag/{--newsList.tag}.{@format}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--newsList':
      '@package': 'Lelesys.Plugin.News'
      '@controller': 'News'
      '@action': 'index'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE

# archive
-
  name: 'Show Archive News'
  uriPattern: '{node}/archive/{--newsList.year}/{--newsList.month}.{@format}'
  defaults:
    '@package': 'TYPO3.Neos'
    '@controller': 'Frontend\Node'
    '@format': 'html'
    '@action': 'show'
    '--newsList':
      '@package': 'Lelesys.Plugin.News'
      '@controller': 'News'
      '@action': 'index'
      '@format': 'html'
  routeParts:
    node:
      handler: TYPO3\Neos\Routing\FrontendNodeRoutePartHandler
  appendExceedingArguments: TRUE
