Lelesys:
  Captcha:
    primaryColor:
      red: 225
      green: 225
      blue: 225
  Plugin:
    News:
      notifications:
        emailTemplatePath: 'Plugins/Lelesys.Plugin.News/Resources/Private/Templates/Emails/CommentApproval.html'
      # set comment publish to 0 for enabling comment before admin approval
      comment:
        publish:
      templateRootPath: 'resource://Lelesys.Plugin.News/Private/Templates/'
      partialRootPath: 'resource://Lelesys.Plugin.News/Private/Partials/'
      layoutRootPath: 'resource://Lelesys.Plugin.News/Private/Layouts/'
      # Default template paths. DO NOT remove these lines
      paginateTemplatePath: 'resource://Lelesys.Plugin.News/Private/Templates/ViewHelpers/Widget/Paginate/Index.html'
      # Set Digital asset width for Thumbail, carousel and icon size
      digitalAsset:
        carouselWidth: 400
        thumbnailWidth: 200
        iconWidth: 60
        # Node Mapping
      targetNodeMappings:
         # From News list to News Detail
        'newsList':
          - package: Lelesys.Plugin.News
            controller: News
            action: show
            targetNode: 05bd8b46-04bc-4ce1-af3c-8d5c8f0ce2e1
            targetNamespace: 'newsDetail'

        # From News latest to News Detail
        'newsLatest':
            # News Detail
          - package: Lelesys.Plugin.News
            controller: News
            action: show
            targetNode: 05bd8b46-04bc-4ce1-af3c-8d5c8f0ce2e1
            targetNamespace: 'newsDetail'

        # From Tag list to News list
        'tagList':
          - package: Lelesys.Plugin.News
            controller: News
            action: index
            targetNode: df340dc6-2df8-2bbf-46dd-df4aa9193193
            targetNamespace: 'newsList'

        # From Category list to News list
        'categoryList':
          - package: Lelesys.Plugin.News
            controller: News
            action: index
            targetNode: df340dc6-2df8-2bbf-46dd-df4aa9193193
            targetNamespace: 'newsList'

        # From Archive list to News list
        'archiveList':
          - package: Lelesys.Plugin.News
            controller: News
            action: index
            targetNode: df340dc6-2df8-2bbf-46dd-df4aa9193193
            targetNamespace: 'newsList'

        # From Tag list to News list
        'folderList':
          - package: Lelesys.Plugin.News
            controller: News
            action: index
            targetNode: df340dc6-2df8-2bbf-46dd-df4aa9193193
            targetNamespace: 'newsList'

# Backend modules configuration
TYPO3:
  Neos:
    modules:
      newsmanagement:
        label: 'News Management'
        controller: '\Lelesys\Plugin\News\Controller\Module\NewsManagementController'
        description: 'Contains multiple modules related to news management of content'
        icon: 'icon-briefcase'
        resource: 'Lelesys_Plugin_News_Module_NewsManagement'
        submodules:
          news:
            label: 'News'
            controller: '\Lelesys\Plugin\News\Controller\Module\NewsManagement\News\NewsController'
            description: 'The News module provides you with an overview of the news. You can edit, add and delete information of news.'
            icon: 'icon-archive'
            resource: 'Lelesys_Plugin_News_Module_NewsManagement_News'
            actions:
              new:
                label: 'Create News'
                title: 'Create news'
          category:
            label: 'Category'
            controller: '\Lelesys\Plugin\News\Controller\Module\NewsManagement\Category\CategoryController'
            description: 'The News module provides you with an overview of the news. You can edit, add and delete information of news.'
            icon: 'icon-archive'
            resource: 'Lelesys_Plugin_News_Module_NewsManagement_Category'
            actions:
              new:
                label: 'Create Category'
                title: 'Create Category'
          comment:
            label: 'Comment'
            controller: '\Lelesys\Plugin\News\Controller\Module\NewsManagement\Comment\CommentController'
            description: 'The News module provides you with an overview of the news. You can edit, add and delete information of news.'
            icon: 'icon-archive'
            resource: 'Lelesys_Plugin_News_Module_NewsManagement_Comment'
          folder:
            label: 'Folder'
            controller: '\Lelesys\Plugin\News\Controller\Module\NewsManagement\Folder\FolderController'
            description: 'The News module provides you with an overview of the news. You can edit, add and delete information of news.'
            icon: 'icon-archive'
            resource: 'Lelesys_Plugin_News_Module_NewsManagement_Folder'
            actions:
              new:
                label: 'Create Folder'
                title: 'Create Folder'
